apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gigahub
resources:
  - namespace.yaml
  - configmap-api.yaml
  - api.yaml
  - api-hpa.yaml
  - web.yaml
  - nginx-configmap.yaml
  - nginx.yaml
  - ingress.yaml
