export type { HealthServiceStatus, HealthCheckResponse } from './lib/health';
export type { ApiErrorEnvelope } from './lib/errors';
export type {
  UserStub,
  PublicUserDto,
  LoginRequestDto,
  LoginResponseDto,
  RenewTokenResponseDto,
  ChangePasswordRequestDto,
  ChangePasswordResponseDto,
  UserListQueryDto,
  UserListItemDto,
  UserDetailDto,
  PaginatedUsersDto,
  InactivateUserResponseDto,
  RoleSummaryDto,
  RoleListItemDto,
  ListRolesResponseDto,
  PermissionDefinitionDto,
  ListPermissionsResponseDto,
  ReplaceRolePermissionsRequestDto,
  ReplaceRolePermissionsResponseDto,
  CreateRoleRequestDto,
  CreateRoleResponseDto,
  UpdateUserRequestDto,
  UpdateUserResponseDto,
  ReplaceUserRolesRequestDto,
  ReplaceUserRolesResponseDto,
  UpdateUserAvatarResponseDto,
} from './lib/identity';
export {
  userStatusSchema,
  publicUserDtoSchema,
  loginRequestDtoSchema,
  loginResponseDtoSchema,
  renewTokenResponseDtoSchema,
  changePasswordRequestDtoSchema,
  changePasswordResponseDtoSchema,
  userListStatusFilterSchema,
  userListQueryDtoSchema,
  userListItemDtoSchema,
  userDetailDtoSchema,
  paginatedUsersDtoSchema,
  inactivateUserResponseDtoSchema,
  roleSummaryDtoSchema,
  roleListItemDtoSchema,
  listRolesResponseDtoSchema,
  permissionDefinitionDtoSchema,
  listPermissionsResponseDtoSchema,
  replaceRolePermissionsRequestDtoSchema,
  replaceRolePermissionsResponseDtoSchema,
  createRoleRequestDtoSchema,
  createRoleResponseDtoSchema,
  updateUserRequestDtoSchema,
  updateUserResponseDtoSchema,
  replaceUserRolesRequestDtoSchema,
  replaceUserRolesResponseDtoSchema,
  updateUserAvatarResponseDtoSchema,
} from './lib/identity';
export {
  geoPointDtoSchema,
  customerStatusSchema,
  customerAddressDtoSchema,
  customerDtoSchema,
  type GeoPointDto,
  type CustomerDto,
} from './lib/customer';
export {
  CUSTOMER_CONSULT_SECTIONS,
  customerSearchQueryDtoSchema,
  customerSearchHitDtoSchema,
  customerSearchResponseDtoSchema,
  customerConsultSectionSchema,
  customerConsultationQueryDtoSchema,
  customerConsultationResponseDtoSchema,
  customerConsultationDataDtoSchema,
  type CustomerConsultSection,
  type CustomerSearchQueryDto,
  type CustomerSearchHitDto,
  type CustomerSearchResponseDto,
  type CustomerConsultationQueryDto,
  type CustomerConsultationResponseDto,
} from './lib/customer-consultation';
export {
  workOrderStatusSchema,
  workOrderDtoSchema,
  subjectDtoSchema,
  type WorkOrderDto,
  type SubjectDto,
} from './lib/work-order';
export {
  careChannelSchema,
  careTicketStatusSchema,
  careInboxDtoSchema,
  careTicketDtoSchema,
  type CareInboxDto,
  type CareTicketDto,
} from './lib/care-inbox';
export {
  DomainEventTypes,
  type DomainEventActor,
  type DomainEventEnvelope,
  type DomainEventType,
  type WorkOrderEventPayload,
  type CareTicketEventPayload,
} from './lib/events';
export {
  nearbyProjectQueryDtoSchema,
  nearbyFiberAccessTerminalDtoSchema,
  nearbyFiberAccessTerminalsResponseDtoSchema,
  nearbyFiberCableDtoSchema,
  nearbyFiberCablesResponseDtoSchema,
  searchProjectNetworkQueryDtoSchema,
  searchProjectNetworkHitDtoSchema,
  searchProjectNetworkResponseDtoSchema,
  type NearbyProjectQueryDto,
  type NearbyFiberAccessTerminalDto,
  type NearbyFiberAccessTerminalsResponseDto,
  type NearbyFiberCableDto,
  type NearbyFiberCablesResponseDto,
  type SearchProjectNetworkQueryDto,
  type SearchProjectNetworkHitDto,
  type SearchProjectNetworkResponseDto,
} from './lib/project-network';
